module.exports = Object.freeze({
  IS_PRODUCTION: process.env.NODE_ENV === 'production',
  VERBOSE_LOGGING: process.env.VERBOSE_LOGGING === 'true',
  API_URL: process.env.CLAIMS_API || 'http://localhost:8081',
  CHANGE_HISTORY_NEW_CLAIM: 'ClaimantDetailsEntered',
  CHANGE_HISTORY_CLAIM_DETAILS_CONFIRMED: 'ClaimantDetailsConfirmed',
  CHANGE_HISTORY_CLAIM_DETAILS_MODIFIED: 'ClaimantDetailsModified',
  CHANGE_HISTORY_CHIB_VERIFIED: 'VerifyChildBenefit',
  CHANGE_HISTORY_CHIB_NOT_VERIFIED: 'UnverifiedChildBenefit',
  CHANGE_HISTORY_REL_VERIFIED: 'VerifyRelationship',
  CHANGE_HISTORY_REL_NOT_VERIFIED: 'UnverifiedRelationship',
  CHANGE_HISTORY_DEATH_VERIFIED: 'VerifyDeath',
  CHANGE_HISTORY_DEATH_NOT_VERIFIED: 'UnverifiedDeath',
  CHANGE_HISTORY_DEPENDENT_CHILDREN_YES: 'ChildrenDetailsEnteredAsTrue',
  CHANGE_HISTORY_DEPENDENT_CHILDREN_YES_PREGNANT: 'ChildrenDetailsEnteredAsTrueAndPregnant',
  CHANGE_HISTORY_DEPENDENT_CHILDREN_NO: 'ChildrenDetailsEnteredAsFalse',
  CHANGE_HISTORY_DEPENDENT_CHILDREN_NO_PREGNANT: 'ChildrenDetailsEnteredAsFalseAndPregnant',
  CHANGE_HISTORY_DISALLOWED_SPA: 'DisallowedForSPA',
  CHANGE_HISTORY_DISALLOW_REL: 'ClaimDisallowedNotMarried',
  CHANGE_HISTORY_DISALLOW_REL_EVIDENCE: 'ClaimDisallowedRelationshipNotVerified',
  CHANGE_HISTORY_DISALLOW_DEATH_EVIDENCE: 'ClaimDisallowedDeathNotVerified',
  CHANGE_HISTORY_ADD_PAYMENT_DETAILS: 'AddPaymentDetails',
  CHANGE_HISTORY_NO_PAYMENT_DETAILS: 'NoPaymentDetails',
  CHANGE_HISTORY_CHANGE_PAYMENT_DETAILS: 'ChangePaymentDetails',
  CHANGE_HISTORY_NICONTS_VERIFIED: 'VerifyNIConts',
  CHANGE_HISTORY_NICONTS_NOT_VERIFIED: 'UnverifiedNIConts',
  CHANGE_HISTORY_RATE: 'ChangedRate',
  DISALLOW_SPA: 'notAsExpected',
  DISALLOW_NI_CONTS: 'notAsExpected',
  DISALLOW_REL: 'notAsExpected',
  DISALLOW_REL_EVIDENCE: 'notVerified',
  DISALLOW_DEATH_EVIDENCE: 'notVerified',
  API_END_POINT_CLAIMS: '/claims',
  API_END_POINT_SCHEDULE: '/schedules',
  API_END_POINT_CLAIMANTS: '/claimants',
  API_END_POINT_DECISION: '/decision',
  API_END_POINT_STOP: '/stop',
  FAKE_NINO: 'QQ999999A'
});
